id: AEE255CAD
title: 'Fully Blossomed Learning and Contemplation: A Praise of the Great Spiritual
  Friend Jamyang Gyaltsen'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:34:12.959481
  last_modified_at: 2022-02-28 23:34:12.959489
